# for more on packages: https://www.home-assistant.io/docs/configuration/packages/
# for more on groups: https://www.home-assistant.io/integrations/group
#   NOTE: these are the new groups not the "old style" (https://www.home-assistant.io/integrations/group#old-style-groups)
# For more on binary_sensor: https://www.home-assistant.io/integrations/binary_sensor/

binary_sensor:
  - platform: group
    name: Perimeter Sensors
    unique_id: perimeter_sensors_group
    device_class: door
    entities:
      - binary_sensor.front_door_deck
      - binary_sensor.kitchen_door
      - binary_sensor.office_sliding_door
      - binary_sensor.living_room_window
      - binary_sensor.dining_window
      - binary_sensor.master_bedroom_window
      - binary_sensor.east_bedroom_window_jonah_s
      - binary_sensor.west_bedroom_window_micah_s
      - binary_sensor.laundry_window
      - binary_sensor.garage_door_sensor_device_access_control_window_door_is_open

  - platform: group
    name: Motion Sensors
    unique_id: motion_sensors_group
    device_class: motion
    entities:
      - binary_sensor.front_motion
      - binary_sensor.master_bedroom_motion
      - binary_sensor.office_motion
